### ISSUE TITLE
GitHub Pages deployment does not use our overrides

### ISSUE THREAD

**Issue by ShanTulshi** [illinois-cs498vr/illinois-cs498vr.github.io#33]

**Comment by ShanTulshi** [comment]
seems like the github pages hosting is breaking our theme overrides.

**Comment by andrewipark** [comment]
Possibly related to the presence of a separate gh-pages branch?

**Comment by ShanTulshi** [comment]
I tried both, serving from `gh-pages` and `master`, but neither will use our overridden layouts.

**Comment by ShanTulshi** [comment]
Resolved. Deployed!
